version: '3'

services:
  app:
    build:
      dockerfile: develop.Dockerfile
    environment:
        NODE_ENV: development
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn dev
    ports:
      - 9876:9876