version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      args:
        NODE_ENV: 'production'
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn dev
    ports:
      - 9876:9876